### ISSUE TITLE
Configure Maven Plugin for Liquibase

### ISSUE THREAD

**Issue by frzhen** [frzhen/sdjpa-intro#1]

**Comment by frzhen** [comment]
<plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>4.6.1</version>
                <configuration>
                    <url>jdbc:mysql://127.0.0.1:3307/bookdb?useUnicode=true&amp;characterEncoding=UTF-8&amp;serverTimezone=UTC</url>
                    <username>bookadmin</username>
                    <password>password</password>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>${mysql.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

**Comment by NotAImbecile** [comment]
[Using Lquibase and your Maven POM file](https://docs.liquibase.com/tools-integrations/maven/using-liquibase-and-maven-pom-file.html)
