### ISSUE TITLE
Configure Spring Boot Support for Liquibase

### ISSUE THREAD

**Issue by frzhen** [frzhen/sdjpa-intro#3]
- [x] Add liquibase dependency in POM
- [x] Add spring.liquibase.change-log=db/changelog/changelog-master.xml to "application.properties"
- [x] Changed the spring.datasource.username to bookuser for normal use in "application-local.properties"
- [x] Add spring.liquibase.user to bookadmin user for database migration usage in "application-local.properties"
- [x] Drop the tables in the bookdb with database tool (Mysql workbench)
- [x] Run the application (which will use the changelog xml files to create table schema

**Comment by NotAImbecile** [comment]
There are some errors in the run, will fix in the next issue
